import type { NextConfig } from "next";

/**
 * Content-Security-Policy.
 *
 * script-src carries 'unsafe-inline' deliberately, and that is the ceiling for
 * this app rather than an oversight. Every page ships 28-42 inline scripts
 * holding the RSC flight payload, so their content differs per page and per
 * build:
 *
 *   - hash-based CSP would need per-page hashes that change on every build, so
 *     it cannot be expressed in a static header;
 *   - nonce-based CSP means reading headers() in a server component, which opts
 *     every route into dynamic rendering and gives up all 37 prerendered pages.
 *
 * What the policy still buys, which is the majority of the value here: no
 * external script can load (the practical defence against a compromised
 * dependency injecting a remote <script>), no exfiltration to another origin,
 * no framing, no base-tag or form-action hijacking, no plugins. The site takes
 * no user input that reaches the DOM as markup — the one untrusted value, the
 * ?c= theme preset, is parsed to clamped numbers in theme-editor.tsx — so there
 * is no injection point for 'unsafe-inline' to widen.
 *
 * style-src needs 'unsafe-inline' for React style attributes, which the theme
 * editor writes on every slider change.
 */
const csp = [
  "default-src 'self'",
  "script-src 'self' 'unsafe-inline'",
  "style-src 'self' 'unsafe-inline'",
  // data: covers the grain noise SVG in globals.css and the inlined duck mark.
  // https: is needed because DuckGlyph renders its mark from a URL — the docs
  // demo it with remote images, and the default mark is the absolute registry
  // URL, which is cross-origin in dev. Images cannot execute, every URL on the
  // site is authored in-repo, and Referrer-Policy already trims what a remote
  // host learns, so this widens pixel loading only.
  "img-src 'self' data: https:",
  // Fonts are downloaded at build time by next/font and served from this origin.
  "font-src 'self'",
  "connect-src 'self'",
  "manifest-src 'self'",
  "object-src 'none'",
  "frame-src 'none'",
  "frame-ancestors 'none'",
  "base-uri 'self'",
  "form-action 'self'",
  "upgrade-insecure-requests",
].join("; ");

const nextConfig: NextConfig = {
  // Emits .next/standalone with a self-contained server.js and only the
  // node_modules it actually traced. Required by the Dockerfile — without it
  // the runner image would need the full dependency tree.
  output: "standalone",

  // The registry JSON in public/r/ is generated by `pnpm registry:build`.

  async headers() {
    return [
      {
        // The registry is consumed by the shadcn CLI and by AI assistants from
        // other origins, so it needs CORS. It is immutable per deploy, hence
        // the long cache with revalidation.
        source: "/r/:path*",
        headers: [
          { key: "Access-Control-Allow-Origin", value: "*" },
          { key: "Access-Control-Allow-Methods", value: "GET, OPTIONS" },
          {
            key: "Cache-Control",
            value: "public, max-age=300, s-maxage=3600, stale-while-revalidate=86400",
          },
        ],
      },
      {
        source: "/:path(llms.txt|llms-full.txt)",
        headers: [
          { key: "Access-Control-Allow-Origin", value: "*" },
          {
            key: "Cache-Control",
            value: "public, max-age=300, s-maxage=3600, stale-while-revalidate=86400",
          },
        ],
      },
      {
        source: "/:path*",
        headers: [
          { key: "Content-Security-Policy", value: csp },
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
          // Matches frame-ancestors 'none' above. Legacy fallback for browsers
          // that do not honour frame-ancestors; the two must not disagree.
          { key: "X-Frame-Options", value: "DENY" },
          {
            key: "Permissions-Policy",
            value: "camera=(), microphone=(), geolocation=(), payment=()",
          },
          {
            key: "Strict-Transport-Security",
            value: "max-age=63072000; includeSubDomains; preload",
          },
        ],
      },
    ];
  },
};

export default nextConfig;
